### PR TITLE
feat: add parse alignment for p tag

### PR DESCRIPTION
**Pull request by LanceRabbit**
#39 

@pavittarx could you please review this PR, if you have any concerns please let me know. Thanks

### CODE REVIEW

**Review by pavittarx — APPROVED** [review]

**Comment by pavittarx** [comment]
Thanks, @LanceRabbit. :+1:

**Comment by LanceRabbit** [comment]
> Thanks, @LanceRabbit. 👍

Thanks for your review @pavittarx, but only you can merge this PR. Still need your favors to finish this process.

**Comment by pavittarx** [comment]
@LanceRabbit I did the Review, but have not been able to test it. I'll merge and get it ready for a release, once done.

**Comment by Thimows** [comment]
@pavittarx @LanceRabbit Any update on this? I see that the last release is from Jun 27, 2021. I also really need support for text alignment in the HTML of the editor

**Pull request merged**
